### ISSUE TITLE
sk_region_addowner(region, world, player) returns an error in SKCompat.

### ISSUE THREAD

**Issue by Pieter12345** [jb-aero/SKCompat#11]
When running the function from either script or interpreter, it returns a stacktrace like this:

Uh oh! You've found an error in SKCompat.
This is an error caused while running your code, so you may be able to find a workaround, but is ultimately an error in SKCompat itself.
The line of code that caused the error was this:
sk_region_addowner('plot-existingPlayer', 'existingWorld', 'existingPlayer')
on or around Interpreter:1.
Please report this error to the developers, and be sure to include the version numbers:
Server version: 1.8.3-R0.1-SNAPSHOT;
CommandHelper version: 3.3.1-SNAPSHOT.2858-;
Loaded extensions and versions:
Core (version 3.3.1);
CHDangerous (version 1.0.1);
CHAdvanced (version 1.0.0);
SKCompat (version 1.1.3);
Here's the stacktrace:
com.laytonsmith.PureUtilities.Common.ReflectionUtils$ReflectionException: java.lang.NoSuchMethodException: com.laytonsmith.abstraction.bukkit.BukkitMCOfflinePlayer.<init>(com.laytonsmith.abstraction.MCOfflinePlayer)
        at com.laytonsmith.PureUtilities.Common.ReflectionUtils.newInstance(ReflectionUtils.java:74)
        at com.zeoldcraft.skcompat.Temp.getOfflinePlayer(Temp.java:43)
        at com.zeoldcraft.skcompat.Temp.GetUser(Temp.java:102)
        at com.zeoldcraft.skcompat.SKWorldGuard$sk_region_addowner.exec(SKWorldGuard.java:1353)
        at com.laytonsmith.core.Script.eval(Script.java:352)
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1908)
        at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1865)
        at com.laytonsmith.commandhelper.CommandHelperInterpreterListener.execute(CommandHelperInterpreterListener.java:169)
        at com.laytonsmith.commandhelper.CommandHelperInterpreterListener.textLine(CommandHelperInterpreterListener.java:131)
        at com.laytonsmith.commandhelper.CommandHelperInterpreterListener$1.run(CommandHelperInterpreterListener.java:70)
        at com.laytonsmith.abstraction.bukkit.BukkitConvertor$1.call(BukkitConvertor.java:309)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftFuture.run(CraftFuture.java:89)
        at org.bukkit.craftbukkit.v1_8_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:677)
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:336)
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:626)
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:534)
        at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NoSuchMethodException: com.laytonsmith.abstraction.bukkit.BukkitMCOfflinePlayer.<init>(com.laytonsmith.abstraction.MCOfflinePlayer)
        at java.lang.Class.getConstructor0(Class.java:2810)
        at java.lang.Class.getDeclaredConstructor(Class.java:2053)
        at com.laytonsmith.PureUtilities.Common.ReflectionUtils.newInstance(ReflectionUtils.java:70)
        ... 17 more

**Comment by Pieter12345** [comment]
Just to add it to the list (even though it's already fixed, but there's no build yet): sk_region_addmember() returns a simlair error in SKCompat.

**Comment by jb-aero** [comment]
There has since been builds, so is this fixed?

**Comment by Pieter12345** [comment]
This has been fixed. I'll close this issue :)
