### ISSUE TITLE
Broken sk_region_members() and sk_region_owners()

### ISSUE THREAD

**Issue by Pieter12345** [jb-aero/SKCompat#3]
Always returns {} while "/region info [region]" returns owners/members as player_, player2_, ...

Also, sk_region_info(...)[1] and sk_region_info()[2] - (owners and members array) appear to be empty.

Software versions:
- CraftBukkit 1.8-R0.1-SNAPSHOT
- WorldEdit bukkit 6.0.2 SNAPSHOT build 3328
- WorldGuard 6.0.0 SNAPSHOT build 1521
- CommandHelper 3.3.1-SNAPSHOT build 2780

**Comment by PseudoKnight** [comment]
This extension is only for CommandHelper builds 2817 and higher. These functions work.

**Comment by Pieter12345** [comment]
I see I've copied that from an outdated list. The server is running on CH build 2817.

To be more specific:

Typed in interpreter: sk_region_intersect('redstone', 'plot-test') - (world and plot exist)

No feedback ingame, this feedback in console:

[11:39:19] [Server thread/WARN]: [CommandHelper] Task #201 for CommandHelper v3.3.1-SNAPSHOT.2817- generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.regions.ProtectedRegion.getIntersectingRegions(Ljava/util/List;)Ljava/util/List;
    at com.zeoldcraft.skcompat.SKWorldGuard$sk_region_intersect.exec(SKWorldGuard.java:390) ~[?:?]
    at com.laytonsmith.core.Script.eval(Script.java:353) ~[?:?]
    at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1908) ~[?:?]
    at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1865) ~[?:?]
    at com.laytonsmith.commandhelper.CommandHelperInterpreterListener.execute(CommandHelperInterpreterListener.java:170) ~[?:?]
    at com.laytonsmith.commandhelper.CommandHelperInterpreterListener.textLine(CommandHelperInterpreterListener.java:131) ~[?:?]
    at com.laytonsmith.commandhelper.CommandHelperInterpreterListener$1.run(CommandHelperInterpreterListener.java:70) ~[?:?]
    at com.laytonsmith.abstraction.bukkit.BukkitConvertor$1.call(BukkitConvertor.java:307) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[craftbukkit.jar:git-Bukkit-a1ce164]
    at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit.jar:git-Bukkit-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:653) [craftbukkit.jar:git-Bukkit-a1ce164]
    at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit.jar:git-Bukkit-a1ce164]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit.jar:git-Bukkit-a1ce164]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_60]

**Comment by PseudoKnight** [comment]
That's an error for issue #2 which [edit: jb-aero] already fixed.

**Comment by jb-aero** [comment]
The original issue is different than the error posted.

**Comment by dddeeefff** [comment]
I am also getting this issue (I've only tested `sk_region_info()` though)

Software versions:
- CraftBukkit version git-Spigot-13716d9-0899683 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)
- WorldEdit version 6.0.2-SNAPSHOT;3360-ddc74114 (slightly modded)
- WorldGuard version 6.0.0-SNAPSHOT.1573-
- CommandHelper version 3.3.1-SNAPSHOT.2822-
- SKCompat prelease v1.0.4

**Comment by PseudoKnight** [comment]
Turns out the one region I tested this on had a group and a couple fake members in it. (_shakes fist at mods_) I can see how it wouldn't return the unique-ids that WorldGuard 6 now uses.

**Comment by jb-aero** [comment]
@PhanaticD pay attention here

So my question to you all is do you want names or UUID's returned? Because you are used to names, but the names I'll be able to return will not be guaranteed to not have changed. If I return UUID's you can do whatever name conversion you need.

**Comment by PhanaticD** [comment]
UUID is fine for me

**Comment by Pieter12345** [comment]
I'd suggest to add an optional boolean to the command for this, but default to names as before. This way, you can be sure the functionality is backwards compatible. Another option could be to create a sk_region_owners_UUID() for people who would like to deal with UUID's.

I guess the real 'fix' should be implemented in the WorldGuard plugin itself; when an UUID doesn't match a playername (on join perhaps), it should just change the new name.

**Comment by jb-aero** [comment]
During my talk with Wizjany I learned that WG does do username caching in order to return names in /rg info, but it only updates when requested. So either we forcefully request it (I haven't seen the performance impact yet), or those who use names accept that they may not be up to date.

That is a good point though, validating the cached username on join shouldn't be too much of it hit, I will check to see if that's already done and if something can be done about it otherwise.

**Comment by PseudoKnight** [comment]
A boolean parameter would have been nice, but I think it's impractical given the functions. I recommend just switching to UUIDs for region owner/member functions. This is one of those things where breaking backwards compatibility is just part of the job due to upstream changes. You can then add additional features later if it becomes apparent that a particular need isn't being met. Because RIGHT NOW, things are impossible. People are already working around the issue. It's too late for a smooth transition.

**Comment by jb-aero** [comment]
Finally fixed by cfac9ea19da3bf72bd5666dab28f71f4ab90cdc8 and 85b7f3ba2c3fbc13a8ecd1e2c90a97ec653c086b
