### ISSUE TITLE
skcb_paste wont initialize with FastAsyncWorldEdit

### ISSUE THREAD

**Issue by PhanaticD** [jb-aero/SKCompat#33]
```
[04:22:14] [Server thread/INFO]: Enabling FastAsyncWorldEdit v17.12.15-0dbb617-949-18.0.6
[04:22:14] [extensionloader/ERROR]: Could not load class 'io.github.jbaero.skcompat.CHWorldEdit.skcb_paste'
[04:22:14] [extensionloader/WARN]: java.lang.LinkageError: loader (instance of  org/bukkit/plugin/java/PluginClassLoader): attempted  duplicate class definition for name: "com/sk89q/worldedit/extent/Extent"
[04:22:14] [extensionloader/WARN]:  at java.lang.ClassLoader.defineClass1(Native Method)
[04:22:14] [extensionloader/WARN]:  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
[04:22:14] [extensionloader/WARN]:  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[04:22:14] [extensionloader/WARN]:  at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[04:22:14] [extensionloader/WARN]:  at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[04:22:14] [extensionloader/WARN]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[04:22:14] [extensionloader/WARN]:  at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[04:22:14] [extensionloader/WARN]:  at java.security.AccessController.doPrivileged(Native Method)
[04:22:14] [extensionloader/WARN]:  at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[04:22:14] [extensionloader/WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105)
[04:22:14] [extensionloader/WARN]:  at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189)
[04:22:14] [extensionloader/WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[04:22:14] [extensionloader/WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90)
[04:22:14] [extensionloader/WARN]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[04:22:14] [extensionloader/WARN]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
[04:22:14] [extensionloader/WARN]:  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[04:22:14] [extensionloader/WARN]:  at java.lang.Class.forName0(Native Method)
[04:22:14] [extensionloader/WARN]:  at java.lang.Class.forName(Class.java:348)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.PureUtilities.Common.ClassUtils.forCanonicalName(ClassUtils.java:121)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.PureUtilities.Common.ClassUtils.forCanonicalName(ClassUtils.java:47)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.PureUtilities.ClassLoading.ClassMirror.ClassReferenceMirror.loadClass(ClassReferenceMirror.java:62)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.PureUtilities.ClassLoading.ClassMirror.ClassMirror.loadClass(ClassMirror.java:421)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.core.extensions.ExtensionManager.Initialize(ExtensionManager.java:453)
[04:22:14] [extensionloader/WARN]:  at com.laytonsmith.commandhelper.CommandHelperPlugin$5.run(CommandHelperPlugin.java:296)
```

**Comment by jb-aero** [comment]
I am getting notifications now! I will look into this

**Comment by PhanaticD** [comment]
I think it might be a race condition or something because it loaded on most all of my other servers without a problem (including this same one yesterday)

**Comment by jb-aero** [comment]
What versions of commandhelper and server software?

**Comment by PhanaticD** [comment]
commandhelper 3289, and paperspigot whatever the latest version is

**Comment by jb-aero** [comment]
I'm having trouble getting FAWE to even load, and then SKCompat doesn't even recognize WorldEdit as loaded it seems. Or rather, WorldEdit appears to load, and then something in the FAWE loading process fails and WE is left unloaded.

**Comment by jb-aero** [comment]
This may or may not be related to #30 , which I still have to handle. I did finally get it set up and was able to use skcb_paste with no issue. I did also push a new minor update which is available on the Jenkins. New version is 2.1.1. Otherwise do these versions match yours?

[01:45:27 INFO]: This server is running Paper version git-Paper-1288 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[01:45:27 INFO]: Checking version, please wait...
[01:45:27 INFO]: You are running the latest version
[01:45:35 INFO]: CommandHelper version 3.3.2-SNAPSHOT.3289-
[01:45:41 INFO]: FastAsyncWorldEdit version 17.12.26-994856b-952-18.0.9
[01:45:41 INFO]: Fast Async WorldEdit plugin
[01:45:41 INFO]: Author: Empire92
[01:52:53 INFO]: WorldEdit version 6.1.9-SNAPSHOT;3719-72d0e0d

**Comment by PhanaticD** [comment]
more or less :P close enough

**Comment by jb-aero** [comment]
Does the new version work?

**Comment by PhanaticD** [comment]
possibly, it only happened once on the old version with a number of servers using it, I will let you know if it does happen again though
