### ISSUE TITLE
Could not pass event BlockPistonExtendEvent (throws errors on piston extension due to removed code in CH).

### ISSUE THREAD

**Issue by Pieter12345** [jb-aero/SKCompat#8]
Since build 2838 of CommandHelper, SKCompat 1.0.0 and SKComat 1.1.0 throw this error in console every time a piston extends: [Error below].

In the update notes of CH build 2838, this is what I believe is causing this error:
- Remove dependency on WorldGuard. Asking a plugin whether to allow a command in one of its zones should be left to a relevant extension. (44ed9c by jb_aero)
  
  [18:08:20] [Server thread/ERROR]: Could not pass event BlockPistonExtendEvent to CommandHelper v3.3.1-SNAPSHOT.2840-
  org.bukkit.event.EventException
          at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[craftbukkit.jar:git-Bukkit-a1ce164]
          at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-a1ce164]
          at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit.jar:git-Bukkit-a1ce164]
          at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.BlockPiston.a(BlockPiston.java:335) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.BlockPiston.a(BlockPiston.java:169) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.WorldServer.a(WorldServer.java:1036) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.WorldServer.ak(WorldServer.java:1022) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.WorldServer.doTick(WorldServer.java:242) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:692) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:598) [craftbukkit.jar:git-Bukkit-a1ce164]
          at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:506) [craftbukkit.jar:git-Bukkit-a1ce164]
          at java.lang.Thread.run(Thread.java:744) [?:1.7.0_45]
  Caused by: java.lang.NoClassDefFoundError: com/laytonsmith/commandhelper/SKHandler
          at com.zeoldcraft.skcompat.SKWorldGuard$sk_regions_at.exec(SKWorldGuard.java:594) ~[?:?]
          at com.laytonsmith.core.Script.eval(Script.java:353) ~[?:?]
          at com.laytonsmith.core.Script.eval(Script.java:322) ~[?:?]
          at com.laytonsmith.core.Script.eval(Script.java:322) ~[?:?]
          at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1908) ~[?:?]
          at com.laytonsmith.core.MethodScriptCompiler.execute(MethodScriptCompiler.java:1865) ~[?:?]
          at com.laytonsmith.core.events.AbstractEvent.execute(AbstractEvent.java:98) ~[?:?]
          at com.laytonsmith.core.events.BoundEvent.execute(BoundEvent.java:320) ~[?:?]
          at com.laytonsmith.core.events.BoundEvent.trigger(BoundEvent.java:278) ~[?:?]
          at com.laytonsmith.core.events.EventUtils.FireListeners(EventUtils.java:254) ~[?:?]
          at com.laytonsmith.core.events.EventUtils.TriggerListener(EventUtils.java:241) ~[?:?]
          at com.laytonsmith.abstraction.bukkit.events.drivers.BukkitBlockListener.onPistonExtend(BukkitBlockListener.java:52) ~[?:?]
          at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source) ~[?:?]
          at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_45]
          at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_45]
          at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:295) ~[craftbukkit.jar:git-Bukkit-a1ce164]
          ... 13 more

**Comment by jb-aero** [comment]
You should be on 1.1.4
